### ISSUE TITLE
CMake: use nc-config and nf-config to find NetCDF libraries

### ISSUE THREAD

**Issue by kilicomu** [LiamBindle/geos-chem#3]
Hi Liam.

I am wondering whether or not it would be a 'cleaner' experience all round if you use the `nc-config` and `nf-config` utilities to confirm the existence of the NetCDF libraries on a user's system.

A contrived example of this would be:

```
find_program(NC_CONFIG NAMES "nc-config" DOC "Location of nc-config utility")
if(NOT NC_CONFIG)
  message(FATAL_ERROR "Failed to find the nc-config utility - is it in your PATH?")
endif()

execute_process(COMMAND ${NC_CONFIG} "--prefix"
  RESULT_VARIABLE NC_CONFIG_RET
  OUTPUT_VARIABLE NETCDF_C_ROOT
  ERROR_VARIABLE NC_CONFIG_STDERR)
if(NOT NC_CONFIG_RET)
  message(FATAL_ERROR "Failed to find NetCDF-C prefix from nc-config - check NetCDF-C installation")
  set(NETCDF_C_ROOT NOTFOUND)
endif() 
```

This would leave you with a variable `NETCDF_C_ROOT` that contains the NetCDF-C installation prefix as known by `nc-config`. The same could be done with `nf-config`.

My assumptions:
* `nc-config` will always be in the `PATH` when building GEOS-Chem
* the prefix reported by the `nc-config` that is first in the `PATH` will always be the prefix of the desired NetCDF installation
* other implicit assumptions that I haven't noticed

The above can obviously be extended to find the headers/include files and libraries from within the `include` and `lib` directories of the NetCDF installations once you have found their roots. You can also get library versions through the `nc-config` and `nf-config` utilities.

Additionally, if you wrap this up in a CMake function, you can avoid propagating all of the internal variables up into the parent scope, specifying only your `OUTPUT_VARIABLE` be propagated upwards for use by the rest of the configure process.

Let me know what you think.

**Comment by LiamBindle** [comment]
Hi Killian,

I like this idea a lot! I'm going to write this up this afternoon, so I'll get back to you later today.

--Liam

**Comment by LiamBindle** [comment]
Hi Killian,

Here is a draft of the new `FindNetCDF.cmake`. If you have the time, could you try replacing `FindNetCDF.cmake`  (in `<GCClassic source code>/CMakeScripts/`) with the `FindNetCDF.cmake` that I have attached? You will have to remove `COMPONENTS F90` from the following line.

https://github.com/LiamBindle/geos-chem/blob/695cda2ae7f021887c8d6a71f6e93fa013875968/CMakeScripts/GC-ConfigureClassicBuild.cmake#L20

Let me know what you think. 

Attachements: 
[FindNetCDF.zip](https://github.com/LiamBindle/geos-chem/files/3208559/FindNetCDF.zip)

Edit: Alternatively, you could retry with `feature/CMake` (currently https://github.com/LiamBindle/geos-chem/commit/bb986e38af37ec6a0daf47bea8167b8b9f99d5c8) which has a number of updates that I've made over the past week (including the updated `FindNetCDF.cmake`).

Thanks,
Liam

**Comment by kilicomu** [comment]
Hi Liam.

Sorry for the delay here.

I have tried configuring and building GEOS-Chem Classic using the `feature/CMake` branch (db365904c5b0597f348f297ba4527f7a7bae2843) - it worked cleanly out of the box.

I will probe its behaviour when tools/libraries aren't in the environment and get back to you with the results.

Killian

**Comment by LiamBindle** [comment]
Hi Killian.

Great! Glad it's working good for you. If you have any suggestions for how I could improve anything, please let me know 😄 

Liam
