### ISSUE TITLE
ifort: deprecated compiler option set by default

### ISSUE THREAD

**Issue by kilicomu** [LiamBindle/geos-chem#4]
Hi Liam.

In the file `GC-ConfigureClassicBuild.cmake`, you set a compiler flag `-vec-report0` as a default compiler flag for release builds, storing it in the CMake variable `CMAKE_Fortran_FLAGS_RELEASE`.

It is worth noting that this compiler option was deprecated in Intel Fortran compiler version 16, and is no longer available in the Intel Fortran compiler. If you think that vectorisation reports are an important feature, you can find details about how to generate a vectorisation report [here](https://software.intel.com/en-us/fortran-compiler-auto-vectorization-tutorial-generating-a-vectorization-report).

I raise this issue simply because a message is generated by `ifort` when building GEOS-Chem:

```
ifort: command line remark #10148: option '-vec-report0' not supported
```

Although the issue doesn't affect the build, it is potentially misleading for users.

Killian

**Comment by yantosca** [comment]
We probably don't need to know about vectorization of loops, unless we are doing performance profiling or testing.  For most GC users that type of feedback is probably overkill, so we omit the flag.

**Comment by LiamBindle** [comment]
Sounds good. I'll remove `-vec-report0` from the release flags. 

Thanks!
